common: &default_client
  options:
    server_selection_timeout: 5
    

common_uri: &default_uri
  uri: <%= ENV['MONGOHQ_URL'] %>

development:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

test:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

production:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

edgeprod:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

edgestage:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

staging:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

loadtest:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true
